language: python
sudo: false
dist: trusty

matrix:
  include:
    # These are quick and often catch errors, so list them first
    - python: 3.7
      env: CHECK_DOCS=1
      dist: xenial
      sudo: required
    - python: 3.7
      env: CHECK_FORMATTING=1
      dist: xenial
      sudo: required
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.8-dev
      dist: xenial
      sudo: required
    - os: osx
      language: generic
      env: MACPYTHON=3.7.0

script:
  - ci/travis.sh
